package com.nd.dwebview.compiler.utils;

/**
 * Some consts used in processors
 *
 * @author Alex <a href="mailto:zhilong.liu@aliyun.com">Contact me.</a>
 * @version 1.0
 * @since 16/8/24 20:18
 */
public class Consts {
    // Generate
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "DWebView";
    public static final String TAG = PROJECT + "::";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY DWEBVIEW.";
    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String NAME_OF_JSAPI = PROJECT + SEPARATOR;

    public static final String PACKAGE_OF_GENERATE_FILE = "com.nd.dwebview.jsapis";
    public static final String PACKAGE_OF_IJSAPI = "com.nd.dwebview.facade.template.IJsApiCache";


    /**
     * Custom interface
     */
    private static final String FACADE_PACKAGE = "com.nd.dwebview.facade";
    /**
     * Log
     */
    static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler ";
    public static final String NO_MODULE_NAME_TIPS = "These no module name, at 'build.gradle', like :\n" +
            "android {\n" +
            "    defaultConfig {\n" +
            "        ...\n" +
            "        javaCompileOptions {\n" +
            "            annotationProcessorOptions {\n" +
            "                arguments = [DWEBVIEW_MODULE_NAME: project.getName()]\n" +
            "            }\n" +
            "        }\n" +
            "    }\n" +
            "}\n";

    /**
     * Options of processor
     */
    public static final String KEY_MODULE_NAME = "DWEBVIEW_MODULE_NAME";

    /**
     * Annotation type
     */
    public static final String ANNOTATION_TYPE_JSAPI = FACADE_PACKAGE + ".annotations.JsApi";
}